import { ToolCategory } from '@prisma/client';

export const TOOL_SEED_DATA = [
  // Calculators
  { slug: 'mortgage', name: 'Mortgage Calculator', description: 'Monthly payment, interest, and amortization', category: ToolCategory.CALCULATOR, tags: ['mortgage', 'loan'], sortOrder: 1 },
  { slug: 'commission', name: 'Commission Calculator', description: 'Gross and net agent commission', category: ToolCategory.CALCULATOR, tags: ['commission', 'agent'], sortOrder: 2 },
  { slug: 'seller-net', name: 'Seller Net Sheet', description: 'Estimate seller proceeds after deductions', category: ToolCategory.CALCULATOR, tags: ['seller', 'net'], sortOrder: 3 },
  { slug: 'closing-costs', name: 'Closing Cost Calculator', description: 'Buyer closing cost estimate', category: ToolCategory.CALCULATOR, tags: ['closing', 'buyer'], sortOrder: 4 },
  { slug: 'roi', name: 'ROI Calculator', description: 'Return on real estate investment', category: ToolCategory.CALCULATOR, tags: ['roi', 'investment'], sortOrder: 5 },
  { slug: 'rental-income', name: 'Rental Income Estimator', description: 'NOI and effective rent projections', category: ToolCategory.CALCULATOR, tags: ['rental', 'income'], sortOrder: 6 },
  { slug: 'affordability', name: 'Affordability Calculator', description: 'Max home price from income and DTI', category: ToolCategory.CALCULATOR, tags: ['affordability', 'dti'], sortOrder: 7 },
  { slug: 'down-payment', name: 'Down Payment Calculator', description: 'Down payment and loan amounts', category: ToolCategory.CALCULATOR, tags: ['down payment'], sortOrder: 8 },
  { slug: 'refinance', name: 'Mortgage Refinance Calculator', description: 'Compare refinance savings and break-even', category: ToolCategory.CALCULATOR, tags: ['refinance'], sortOrder: 9 },
  { slug: 'cash-flow', name: 'Cash Flow Calculator', description: 'Monthly and annual rental cash flow', category: ToolCategory.CALCULATOR, tags: ['cash flow'], sortOrder: 10 },
  { slug: 'cap-rate', name: 'Cap Rate Calculator', description: 'Capitalization rate from NOI', category: ToolCategory.CALCULATOR, tags: ['cap rate'], sortOrder: 11 },
  { slug: 'mortgage-payoff', name: 'Mortgage Payoff Calculator', description: 'Payoff timeline with extra payments', category: ToolCategory.CALCULATOR, tags: ['payoff'], sortOrder: 12 },
  { slug: 'dti', name: 'Debt-to-Income Ratio', description: 'Front-end and back-end DTI', category: ToolCategory.CALCULATOR, tags: ['dti'], sortOrder: 13 },
  { slug: 'price-per-sqft', name: 'Price Per Square Foot', description: 'Price density for listings', category: ToolCategory.CALCULATOR, tags: ['price', 'sqft'], sortOrder: 14 },
  { slug: 'appreciation', name: 'Property Appreciation', description: 'Gain and annualized appreciation', category: ToolCategory.CALCULATOR, tags: ['appreciation'], sortOrder: 15 },
  { slug: 'investment-analyzer', name: 'Investment Analyzer', description: 'Cash-on-cash and projected equity', category: ToolCategory.CALCULATOR, tags: ['investment'], sortOrder: 16 },
  { slug: 'offer-comparison', name: 'Offer Comparison', description: 'Rank multiple purchase offers', category: ToolCategory.CALCULATOR, tags: ['offers'], sortOrder: 17 },
  // Global
  { slug: 'currency', name: 'Currency Converter', description: 'Live exchange rates', category: ToolCategory.GLOBAL, tags: ['currency', 'fx'], sortOrder: 20 },
  { slug: 'world-clock', name: 'World Clock', description: 'Current time in major cities', category: ToolCategory.GLOBAL, tags: ['time', 'clock'], sortOrder: 21 },
  { slug: 'timezone-compare', name: 'Time Zone Comparison', description: 'Compare zones side by side', category: ToolCategory.GLOBAL, tags: ['timezone'], sortOrder: 22 },
  { slug: 'meeting-planner', name: 'Meeting Planner', description: 'Plan international meetings', category: ToolCategory.GLOBAL, tags: ['meeting'], sortOrder: 23 },
  { slug: 'date-difference', name: 'Date Difference', description: 'Days between two dates', category: ToolCategory.GLOBAL, tags: ['date'], sortOrder: 24 },
  { slug: 'time-duration', name: 'Time Duration', description: 'Sum hours, minutes, seconds', category: ToolCategory.GLOBAL, tags: ['duration'], sortOrder: 25 },
  { slug: 'weather', name: 'Weather Lookup', description: 'Current weather by coordinates', category: ToolCategory.GLOBAL, tags: ['weather'], sortOrder: 26 },
  { slug: 'utc-converter', name: 'UTC/GMT Converter', description: 'Convert between UTC offsets', category: ToolCategory.GLOBAL, tags: ['utc', 'gmt'], sortOrder: 27 },
  { slug: 'city-distance', name: 'City Distance', description: 'Distance between two coordinates', category: ToolCategory.GLOBAL, tags: ['distance', 'cities'], sortOrder: 28 },
  { slug: 'holidays', name: 'Holiday Calendar', description: 'Public holidays by country', category: ToolCategory.GLOBAL, tags: ['holidays'], sortOrder: 29 },
  // Converters
  { slug: 'sqft-sqm', name: 'Sq Ft ↔ Sq M', description: 'Area conversion', category: ToolCategory.CONVERTER, tags: ['area'], sortOrder: 40 },
  { slug: 'acres-hectares', name: 'Acres ↔ Hectares', description: 'Land area conversion', category: ToolCategory.CONVERTER, tags: ['area', 'land'], sortOrder: 41 },
  { slug: 'feet-meters', name: 'Feet ↔ Metres', description: 'Length conversion', category: ToolCategory.CONVERTER, tags: ['length'], sortOrder: 42 },
  { slug: 'inches-cm', name: 'Inches ↔ CM', description: 'Small length conversion', category: ToolCategory.CONVERTER, tags: ['length'], sortOrder: 43 },
  { slug: 'weight', name: 'Weight Converter', description: 'Kg and pounds', category: ToolCategory.CONVERTER, tags: ['weight'], sortOrder: 44 },
  { slug: 'temperature', name: 'Temperature Converter', description: 'Celsius, Fahrenheit, Kelvin', category: ToolCategory.CONVERTER, tags: ['temperature'], sortOrder: 45 },
  { slug: 'volume', name: 'Volume Converter', description: 'Liters and gallons', category: ToolCategory.CONVERTER, tags: ['volume'], sortOrder: 46 },
  { slug: 'distance', name: 'Distance Converter', description: 'Miles and kilometers', category: ToolCategory.CONVERTER, tags: ['distance'], sortOrder: 47 },
  { slug: 'height', name: 'Height Converter', description: 'Feet and meters', category: ToolCategory.CONVERTER, tags: ['height'], sortOrder: 48 },
  { slug: 'area-general', name: 'Area Converter', description: 'Sq ft and acres', category: ToolCategory.CONVERTER, tags: ['area'], sortOrder: 49 },
];
